### ISSUE TITLE
npm run build on windows machine

### ISSUE THREAD

**Issue by wouterdialogic** [yyx990803/laravel-vue-cli-3#12]
Hi, this is the response when running npm run build

 npm run build

> frontend@0.1.0 build C:\x\htdocs\vueclitest\frontend
> rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: [x]
npm ERR!     

Extra info:
the command runs fine in another project.
rm -rf is the linux variant, how can i change this to the windows variant?

for completeness, here is the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\bin\\node\\node.exe',
1 verbose cli   'C:\\bin\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~build: PATH: C:\bin\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\x\htdocs\vueclitest\frontend\node_modules\.bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\x\php;C:\ProgramData\ComposerSetup\bin;C:\bin\Git\cmd;C:\bin\node\;C:\Users\Game PC\AppData\Local\Microsoft\WindowsApps;C:\Users\Game PC\AppData\Roaming\Composer\vendor\bin;C:\Users\Game PC\AppData\Roaming\npm;C:\Program Files (x86)\Yarn\bin
9 verbose lifecycle frontend@0.1.0~build: CWD: C:\x\htdocs\vueclitest\frontend
10 silly lifecycle frontend@0.1.0~build: Args: [ '/d /s /c',
10 silly lifecycle   'rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean' ]
11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.1.0 build: `rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\bin\node\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\bin\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd C:\x\htdocs\vueclitest\frontend
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\bin\\node\\node.exe" "C:\\bin\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 build: `rm -rf ../public/{js,css,img} && vue-cli-service build --no-clean`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by emanuelmutschlechner** [comment]
Check my pull request #13 

First run `npm install rimraf --save-dev` and then replace `rm -rf` with `rimraf` in your `package.json`
https://github.com/yyx990803/laravel-vue-cli-3/blob/05920cc9ecae93d9d1427e1d8d3f81e0dc110277/frontend/package.json#L18
https://github.com/yyx990803/laravel-vue-cli-3/blob/05920cc9ecae93d9d1427e1d8d3f81e0dc110277/frontend/package.json#L7

**Comment by hodler-buidler** [comment]
Well, the solution above has solved the similar problem for me. Worth trying.

**Comment by yyrcn** [comment]
u can use git bash
