### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by IgorDePaula** [yyx990803/laravel-vue-cli-3#7]
Not generate thml file, not put js and css on public folder, in production or development.

**Comment by IgorDePaula** [comment]
Now working only build task, serve task do success but on browser nothing is show, nothing is serving (looking in devtools).

**Comment by IgorDePaula** [comment]
Sometimes I receive this error 
```

URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:574:18)
    at next (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:317:13)
    at /home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:335:12)
    at next (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:275:10)
    at query (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:317:13)
    at /home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/igor/projetos/tandlev2/frontend/node_modules/express/lib/router/index.js:335:12)
```
In serve task

**Comment by IgorDePaula** [comment]
Sorry, I forked this project some days ago, and now I saw some differences. I updated the local project and works fine.

Thanks for wonderful tool, Vue, and sorry for issue.
